Sprint 3
enc2b1q/middle.messenger.praktikum.yandex pull request #13
Opened 2022-12-08 23:11 UTC by enc2b1q

2022-12-08 23:14 UTC, enc2b1q commented
> No mocha in package.json
Изменился спринт 3: тесты во время 3 спринта перенесли на следующий спринт.

2022-12-09 03:50 UTC, maks88sgt requested changes
Привет! Вы отлично потрудились. Чтобы двигаться дальше предлагаю внести следующие изменения:
1. Добавить обработку ошибок ко всем методам взаимодействия с апи.
2. Почистить код от комментариев и отладочных console.log.
3. Немного поправить функционал чата:
* После отправки сообщения стоит очистить поле ввода сообщения.
* Не реализована функция удаления чата.
* Чтобы окрылись сообщения чата приходится кликать по чату дважды, что немного не юзерфрендли (я сначала подумал, что что-то сломалось).

2022-12-09 03:50 UTC, maks88sgt commented on src/api/authApi.ts
> +// }
Ненужный код лучше сразу удалять, чтобы не захламлять проект

2022-12-09 03:50 UTC, maks88sgt commented on src/components/backArrowBtn/index.ts
> +        console.log('backArrowBtn render');
Отладочную информацию лучше удалять из проекта перед мерджем с основной веткой.

2022-12-09 03:50 UTC, maks88sgt commented on src/components/backArrowBtn/style.scss
> +  background-color: #3369F3;
Такие значения лучше использовать через переменные. Это улучшает поддерживаемость кода и облегчает возможные будущие изменения.

2022-12-09 03:50 UTC, maks88sgt commented on src/components/formLogin/style.scss
> +}
Здесь гит ругается на отсутствие EOF. Тут можно почитать почему это важно https://moviecultists.com/when-to-use-eof. Лучше настроить IDE, чтобы это делалось автоматически.

2022-12-09 03:50 UTC, maks88sgt commented on src/controllers/authController.ts
> +        const user = await AuthApi.getUserInfo();
Везде, где вы обращаетесь к АПИ и делаете запросы к серверу следует добавить обработку возможных ошибок на случай проблем с выполнением этих запросов. С учетом того, что вы делаете все через async/await оптимальным будет использовать try/catch на уровне api клиента.

2022-12-09 03:50 UTC, maks88sgt commented on src/controllers/baseController.ts
> +        try {
Работу с АПИ стоит организовать примерно как здесь, но лучше вынести это на уровень соответствующего апи клиента.

2022-12-09 03:50 UTC, maks88sgt commented on src/controllers/userController.ts
> +            let dataToSend = resObj.object;
Значение переменной не меняется в процессе исполнения кода, поэтому лучше будет использовать const при объявлении.

2022-12-09 03:50 UTC, maks88sgt commented on src/controllers/userController.ts
> +        if (!files || !!files && files.length === 0) {
Довольно странное условие, думаю можно его сделать более читаемым

2022-12-09 03:50 UTC, maks88sgt commented on src/services/ws.ts
> +    private urlPrefix = 'wss://ya-praktikum.tech/ws/chats';
Такие глобальные значения лучше вытаскивать в переменные окружения.

2022-12-09 03:50 UTC, maks88sgt commented on src/main/index.ts
> +    .use("/index.html", PageLogin)
В целом при SPA подходе *.html роуты можно опустить.

2022-12-09 03:50 UTC, maks88sgt commented on src/services/interfaces.ts
> +export interface IUserInfo {
Использование префикса I сейчас довольно редко встречается. Это [венгерская нотация](https://ru.wikipedia.org/wiki/Венгерская_нотация) от которой уже практически отказались.

2022-12-10 01:19 UTC, enc2b1q commented
> Привет! Вы отлично потрудились. Чтобы двигаться дальше предлагаю внести следующие изменения:
> 
> 1. Добавить обработку ошибок ко всем методам взаимодействия с апи.
Устранено
> 2. Почистить код от комментариев и отладочных console.log.
Устранено
> 3. Немного поправить функционал чата:
Устранено
> 
> * После отправки сообщения стоит очистить поле ввода сообщения.
Устранено
> * Не реализована функция удаления чата.
(реализована дополнительная к заданиям функция удаления)
> * Чтобы окрылись сообщения чата приходится кликать по чату дважды, что немного не юзерфрендли (я сначала подумал, что что-то сломалось).
Устранено
> 
> 4. Еще стоит поправить код, чтобы проходили автоматические тесты на гитхабе.
Устранено

Устранены все критические и основные замечания.

2022-12-10 01:19 UTC, enc2b1q commented on src/api/authApi.ts
> +// }
Устранено

2022-12-10 01:19 UTC, enc2b1q commented on src/components/backArrowBtn/index.ts
> +        console.log('backArrowBtn render');
Устранено

2022-12-10 01:20 UTC, enc2b1q commented on src/components/backArrowBtn/style.scss
> +  background-color: #3369F3;
Согласен

2022-12-10 01:20 UTC, enc2b1q commented on src/components/formLogin/style.scss
> +}
Согласен. Устранено. 
Настроил в IDE - спасибо за мысль!

2022-12-10 01:23 UTC, enc2b1q commented on src/controllers/authController.ts
> +        const user = await AuthApi.getUserInfo();
Устранено.
В основном по всему проекту это уже было в обработчиках ошибок .then().catch();
В указанной функции изначально было специально так сделано, дальше уровнем выше в вызовах обработчики были. Откорректировал, изменил.

2022-12-10 01:25 UTC, enc2b1q commented on src/controllers/userController.ts
> +            let dataToSend = resObj.object;
Конечно) Всегда использую const по логике. Была необходимость в let, изменялись значения, выводились. В итоге после удаления осталось в let. Исправил.

2022-12-10 01:33 UTC, enc2b1q commented on src/controllers/userController.ts
> +        if (!files || !!files && files.length === 0) {
Согласен, если есть другое видение как. 
Вообще, это - стандартное давно используемое условие: в данном случае - проверки на отсутствие значения (д.б. массив), или что значение (объект массив) есть, но пустой - нулевой длины.

Т.е. отсутствие фактических данных в пришедшей переменной.

2022-12-10 01:36 UTC, enc2b1q commented on src/services/ws.ts
> +    private urlPrefix = 'wss://ya-praktikum.tech/ws/chats';
Согласен. Архитектуру во многих вопросах (включая теорию) можно вообще поменять сильно.
В данном случае для тестового приложения сделана жесткая привязка для одного сервиса.

2022-12-10 01:58 UTC, enc2b1q commented on src/main/index.ts
> +    .use("/index.html", PageLogin)
Согласен, они лишние. Оставались, чтобы с .html и без можно было заходить. Но, фактически, они не нужны.

2022-12-10 01:59 UTC, enc2b1q commented on src/services/interfaces.ts
> +export interface IUserInfo {
Привык. Буду знать, спасибо.
Какие варианты рекомендуются взамен?

2022-12-10 17:36 UTC, maks88sgt commented on src/services/interfaces.ts
> +export interface IUserInfo {
Совсем без префиксов. Вот например https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md

2022-12-10 17:40 UTC, maks88sgt commented on src/controllers/userController.ts
> +        if (!files || !!files && files.length === 0) {
Например так явно будет понятно что тут проверяется
```suggestion
        if (Array.isArray(files); && files.length === 0) {
```

2022-12-10 17:57 UTC, maks88sgt approved these changes
Привет, теперь проект стал гораздо чище. Работу принял, успехов на курсе!

2022-12-11 10:03 UTC, maks88sgt approved these changes
Привет. Очень оперативно все поправлено. Работу принял. 
Единственный не очень хороший момент состоит в том, что использование window считается плохой практикой, т.к. это примерно то же самое, что и использование глобальных переменных. Отличным решением было бы использовать singlton для для доступа к экземплярам роутера и т.д.. Можно создавать экземпляр класса на уровне модуля в котором описан класс и экспортировать из модуля только этот экземпляр, а не класс. Так можно быть уверенным что везде используется один и тот же экземпляр класса.
```JavaScript
const router = new Router();
export router as Router

2022-12-11 10:13 UTC, merged

2022-12-11 11:22 UTC, enc2b1q commented
> Можно создавать экземпляр класса на уровне модуля в котором описан класс и экспортировать из модуля только этот экземпляр, а не класс. Так можно быть уверенным что везде используется один и тот же экземпляр класса.
> 
> ```js
> const router = new Router();
> export router as Router
> ```

Хорошо, спасибо, логично.
Это роутер из теории (такой кривенький синглтон), внутри статическое свойство экземпляра, которое всегда отдается, если заполнено, иначе инициализируется новым экземпляром. На мой взгляд, экспортировать экземпляр вместо класса нагляднее. Решил попробовать использовать то, что дают.